### ISSUE TITLE
Error migrating from eclipse 2021-12 to 2022-03

### ISSUE THREAD

**Issue by tullio0106** [tesla/m2eclipse-mavenarchiver#15]
I migrated my eclipse version from 2021-12 to 2022-03.
On every project I tried to open I get one or more maven build problem.
If I reopen the same project with the 2012-12 (I saved it) it works again .
How can I solve that blocking issue ?
Tks
`Description Resource Path Location Type
null (org.apache.maven.plugins:maven-jar-plugin:3.2.2:jar:default-jar:package)

org.eclipse.core.runtime.OperationCanceledException
at org.eclipse.core.runtime.SubMonitor.checkCanceled(SubMonitor.java:602)
at org.eclipse.core.internal.resources.Resource.setDerived(Resource.java:1620)
at org.eclipse.m2e.core.internal.M2EUtils.createFolder(M2EUtils.java:86)
at org.sonatype.m2e.mavenarchiver.internal.AbstractMavenArchiverConfigurator.writePom(AbstractMavenArchiverConfigurator.java:840)
at org.sonatype.m2e.mavenarchiver.internal.AbstractMavenArchiverConfigurator$1.build(AbstractMavenArchiverConfigurator.java:180)
at org.eclipse.m2e.core.internal.builder.MavenBuilderImpl.build(MavenBuilderImpl.java:135)
at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:169)
at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:1)
at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.lambda$1(MavenBuilder.java:114)
at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:182)
at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:117)
at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.lambda$0(MavenBuilder.java:105)
at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:182)
at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:156)
at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:103)
at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.execute(MavenBuilder.java:88)
at org.eclipse.m2e.core.internal.builder.MavenBuilder.build(MavenBuilder.java:198)
at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:860)
at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:232)
at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:281)
at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:334)
at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:337)
at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:392)
at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:417)
at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:161)
at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:255)
at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
pom.xml /izpack-custom line 4 Maven Build Problem`

**Comment by lohcve** [comment]
same issue！any resolution？
